services:
  postgres:
    image: postgres:17.4
    container_name: koboxingclub-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: koboxingclub_db
    ports:
      - "5432:5432"
    volumes:
      - koboxingclub_pgdata:/var/lib/postgresql/data

volumes:
  koboxingclub_pgdata: